config/routes.rb
Whetstone::Application.routes.draw do
  root :to => "home#index"
  devise_for :users

  resources :comments, :discussions, :resources_stones do
    resources :votes
  end

  resources :stones_users

  resources :stones do
    resources :stones_users
    
    collection do
      post 'search'
    end
    
    post 'update_queue' => 'stones_users#update_queue'
  end

  resources :resources

  resources :users, only: [:show]

  resources :discussions do
    resources :comments
  end

  resources :stones do
    resources :resources
    resources :discussions
  end

  resources :saved_resources

  resources :resources_stones do
    resources :saved_resources
  end


  get "/stones/:id/overview" => "stones#overview", as: "stone_overview"

  get "/resources/:stone_id/filter/:filter" => "resources#filter", as: "filter_resources"

  get "/messages" => "messages#index", as: 'messages'
  get "/messages/:id" => "messages#show", as: "message"
  post "/messages" => "messages#create", as: "new_message"
  post '/users_search' => "users#search"


end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :body, :from_id, :to_id

  belongs_to :from, :class_name => "User", :foreign_key => "from_id"
  belongs_to :to, class_name: "User", foreign_key: "to_id"

  validates :body, :from_id, :to_id, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    if  current_user
      @partners = current_user.message_partners
    else
      redirect_to new_user_session_path
    end
  end

  def show
    @partner = User.find(params[:id])
    @messages = current_user.messages_with(@partner)
    @message = Message.new(to_id: @partner.id)
    render :show, layout: false
  end

  def create
    message = Message.create(params[:message])
    render partial: 'message', locals: { current_user: current_user, partner: message.to, message: message}
  end
end

app/views/messages/_message.html.haml
- if message.from==current_user
  %li.from
    %img{src: gravatar(current_user, 40)}
    %span= message.body
- if message.from==partner
  %li.to
    %img{src: gravatar(partner, 40)}
    = message.body

app/views/messages/_messages.html.haml
#messages
  - messages.each do |message|
    = render partial: "message", locals: {current_user: current_user, partner: partner, message: message}

app/views/messages/index.html.haml
#user_search
  .form
    %h2 Who would you like to message?
    = form_for :user, html: { id: 'user' } do |f|
      .fields
        = f.text_field :username
      .submit_button
        = f.submit "Search", class: "btn btn-primary"
  #results


#current
  %h2 Your Current Conversations
  - @partners.each do |partner|
    %li= link_to "Conversation with #{partner.name}", message_path(partner)

app/views/messages/show.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Whetstone"
      %meta{:content => content_for?(:description) ? yield(:description) : "Whetstone", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        %link{ href: "//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css", rel: "stylesheet"}
        = javascript_include_tag "application"
        = csrf_meta_tags
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" type="text/css" />
        = yield(:head)
  .avgrund-cover
  %body{:class => "avgrund-contents"}
    .wrapper
      - if user_signed_in?
        .left_nav
          .gravatar
            %img{ src: gravatar(current_user,120) }
          %p= link_to current_user.name, edit_user_registration_path
          .mini-search
            = form_tag search_stones_path, remote: true do
              = hidden_field_tag :mini_search, "true"
              = text_field_tag :query, nil, placeholder: "&#xf002; Type Something...".html_safe
          %ul.goals
            %li
              = link_to '<i class="icon-home"></i> Home'.html_safe, root_path
            %li
              = link_to '<i class="icon-envelope"></i> Messages'.html_safe, messages_path
            %li
              = link_to '<i class="icon-trophy"></i> Create Stone'.html_safe, new_stone_path
            %li
              = link_to '<i class="icon-signout"></i> Logout'.html_safe, destroy_user_session_path, :method=>'delete'
            - if current_user.stones
              %h2
                = '<i class="icon-trophy"></i> Goals'.html_safe
              = render current_user.stones

      .meny
        #main{ :role => "main" }
          .right-tabs-fixed
            = yield :right_tabs
          .container
            = render 'layouts/top_navigation'
            = render 'layouts/messages'
            .content
              #messages_headers
                %h1= "Your chat with #{@partner.name}"
                - if @partner.goals.empty?
                  %h2= "#{@partner.name} hasn't set any goals yet! Why not ask what's up?"
                - else
                  %h2= "#{@partner.name} is working on #{@partner.goals.sample.stone.title}! Why not ask how it's going?"
              = render partial: "messages", locals: {partner: @partner, messages: @messages}
              %a#bottom
            #send
              .form
                = form_for(@message, remote: true) do |f|
                  .fields
                    =f.hidden_field  :to_id, value: @partner.id
                    =f.hidden_field :from_id, value: current_user.id
                    =f.text_area :body, rows: 3, required: true
                    =f.submit "Send"

      / ! end of .container
    / ! end of #main