config/routes.rb
Whetstone::Application.routes.draw do
  root :to => "home#index"
  devise_for :users

  resources :comments, :discussions, :resources_stones do
    resources :votes
  end

  resources :stones_users

  resources :stones do
    resources :stones_users
    
    collection do
      post 'search'
    end
    
    post 'update_queue' => 'stones_users#update_queue'
  end

  resources :resources

  resources :users, only: [:show]

  resources :discussions do
    resources :comments
  end

  resources :stones do
    resources :resources
    resources :discussions
  end

  resources :saved_resources

  resources :resources_stones do
    resources :saved_resources
  end


  get "/stones/:id/overview" => "stones#overview", as: "stone_overview"

  get "/resources/:stone_id/filter/:filter" => "resources#filter", as: "filter_resources"

  get "/messages" => "messages#index", as: 'messages'
  get "/messages/:id" => "messages#show", as: "message"
  post "/messages" => "messages#create", as: "new_message"
  post '/users_search' => "users#search"


end

app/models/stone.rb
class Stone < ActiveRecord::Base
  attr_accessible :title, :description

	validates :title, uniqueness: true
	validates :title, presence: true

  has_many :stones_users
	has_many :users, through: :stones_users

  has_many :resources_stones
  has_many :resources, through: :resources_stones

  has_many :discussions
end

app/controllers/stones_controller.rb
class StonesController < ApplicationController

  def show
    @stone = Stone.find(params[:id])
    @goal = current_user.goals.where(stone_id: @stone.id).first if user_signed_in?
  end

  def new
    authenticate_user!
    @stone = Stone.new(title: session[:query])
    session.delete(:query)
  end

  def create
    @stone = Stone.create(params[:stone])
    flash[:success] = "Created a new Stone!"
    redirect_to stone_path(@stone)
  end

  def overview
    @stone = Stone.find(params[:id])
    @goal = current_user.goals.where(stone_id: @stone.id).first if user_signed_in?
    render :json => render_to_string(partial: 'stones/overview', locals: { stone: @stone, goal: @goal }, layout: false).to_json
  end

  def search
    @stones = Stone.basic_search(params[:query])
    search_results = {}
    search_results[:query] = params[:query]
    session[:query] = params[:query]
    
    if @stones.count.zero?
      search_results[:results_html] = render_to_string(partial: 'home/no_results', locals: {failed_query: params[:query] })
    else
      search_results[:results_html] = render_to_string(partial: 'home/search_results', collection: @stones, as: :stone)
    end

    if params[:mini_search]
      search_results[:mini] = true
      search_results[:index_html] = render_to_string('home/index', layout: false)
    end

    render :json => search_results.to_json
  end
end

app/helpers/stones_helper.rb
module StonesHelper
	def current_user_id
		current_user.id rescue "" # TODO: I don't get this
	end
end

app/views/stones/_overview.html.haml
#stone{data: {user_id: "#{current_user_id}", stone_id: stone.id}}
  .stoneheader
    .wrapper
      .title
        %i{ class: "icon-list" }
          = stone.title
      .links
        - if goal.nil?
          = link_to "Add To Your Goals", stone_stones_users_path(stone), class: "btn btn-primary add_goal", remote: true, method: :post
        - else
          = link_to "Delete :-(", stone_stones_user_path(stone, goal), data: { id: "#{goal.id}" }, method: :delete, class: "btn btn-danger delete_goal"
    .description
      = truncate(stone.description, length: 100)
  - unless goal.nil?
    .resources.sortable
      - if goal.queued_items.blank?
        .no_queued_items_message
          How about adding some #{ link_to "Resources", stone_resources_path(stone), remote: true, class: 'get_resources' } to help you accomplish this goal?
      = render partial: 'saved_resources/resources_stone', collection: goal.queued_items, as: :saved_resource
%script
  var url=window.location.pathname+"/update_queue"
  $(document).find('.sortable').sortable({
  update: function(){
  $.post(url, {queue: $(this).sortable('toArray')})
  }
  });
  $( ".sortable" ).disableSelection();

app/views/stones/_stone.html.haml
%li=link_to truncate(stone.title, length: 30), stone_path(stone)

app/views/stones/new.html.haml
#stone
  .form
    %h1 Create a Stone
    .form
      = form_for @stone, url: stones_path, method: 'POST', html: { class: "form-vertical", data: { validate: "parsley", novalidate: ""} } do |f|
        .fields
          = f.label :title
          = f.text_field :title, placeholder: "eg: I want to learn Javascript", data: { trigger: 'change', required: 'true', maxlength: '100', minlength: '5', notblank: 'true' }
          = f.label :description
          = f.text_area :description, rows: 5, data: { trigger: 'change', maxlength: '250', minlength: '5'}
        .submit_button
          = f.submit "Create Stone", class: 'btn btn-primary'

app/views/stones/search.html.haml
%h1 I WANT TO KNOW WHERE THIS THING IS BEING USED
%ul
- @stones.each do |stone|
  %li
    = link_to stone.title, stone_path(stone)

app/views/stones/show.html.haml
- content_for :right_tabs do
  .fixed_tab.get_overview
    = link_to stone_overview_path(@stone) , remote: true do
      %i{ class: 'icon-list' } List
  .fixed_tab.get_discussions
    = link_to stone_discussions_path(@stone), remote: true do
      %i{ class: 'icon-comments'} Discussion
  .fixed_tab.get_resources.active
    = link_to stone_resources_path(@stone), remote: true do
      %i{ class: 'icon-bookmark' } Resources
= render partial: 'resources/index', locals: { stone: @stone, goal: @goal }