config/routes.rb
Whetstone::Application.routes.draw do
  root :to => "home#index"
  devise_for :users

  resources :comments, :discussions, :resources_stones do
    resources :votes
  end

  resources :stones_users

  resources :stones do
    resources :stones_users
    
    collection do
      post 'search'
    end
    
    post 'update_queue' => 'stones_users#update_queue'
  end

  resources :resources

  resources :users, only: [:show]

  resources :discussions do
    resources :comments
  end

  resources :stones do
    resources :resources
    resources :discussions
  end

  resources :saved_resources

  resources :resources_stones do
    resources :saved_resources
  end


  get "/stones/:id/overview" => "stones#overview", as: "stone_overview"

  get "/resources/:stone_id/filter/:filter" => "resources#filter", as: "filter_resources"

  get "/messages" => "messages#index", as: 'messages'
  get "/messages/:id" => "messages#show", as: "message"
  post "/messages" => "messages#create", as: "new_message"
  post '/users_search' => "users#search"


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    flash.delete(:query)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_no_results.html.haml
%h2 No Results Found :-(
%p
  Maybe You Should Start A Community for
  = link_to failed_query, new_stone_path

app/views/home/_search_results.html.haml
.search_result
  .title
    = link_to stone.title, stone_path(stone)
  .description
    = truncate(stone.description, length: 20)
  .members
    = stone.stones_users.count.to_s + " Members"
  .resources
    = stone.resources.count.to_s + " Resources"

app/views/home/index.html.haml
#home
  #animated
    .motto
      .item Build a Community.
      .item Set a Goal.
      .item Stay Sharp.
      = image_tag( "logo.png", id: "logo")
  #search
    .title_wrapper
      %h1 What do you want to learn?
    = form_tag search_stones_path, remote: true do
      = text_field_tag :query, nil, placeholder: "&#xf002; Type Something...".html_safe
  .results