config/routes.rb
Whetstone::Application.routes.draw do
  root :to => "home#index"
  devise_for :users

  resources :comments, :discussions, :resources_stones do
    resources :votes
  end

  resources :stones_users

  resources :stones do
    resources :stones_users
    
    collection do
      post 'search'
    end
    
    post 'update_queue' => 'stones_users#update_queue'
  end

  resources :resources

  resources :users, only: [:show]

  resources :discussions do
    resources :comments
  end

  resources :stones do
    resources :resources
    resources :discussions
  end

  resources :saved_resources

  resources :resources_stones do
    resources :saved_resources
  end


  get "/stones/:id/overview" => "stones#overview", as: "stone_overview"

  get "/resources/:stone_id/filter/:filter" => "resources#filter", as: "filter_resources"

  get "/messages" => "messages#index", as: 'messages'
  get "/messages/:id" => "messages#show", as: "message"
  post "/messages" => "messages#create", as: "new_message"
  post '/users_search' => "users#search"


end

app/views/resources/_form.html.haml
.modal{ class: "avgrund-popup" }
  = form_for [stone, resource], remote: true, html: { class: "create_resource form-horizontal" } do |f|
    .fields
      = f.label :title
      = f.text_field :title
      = f.label :description
      = f.text_area :description, input_html: { rows: 5 }
      = f.label :url
      = f.url_field :url
      = f.label :recommended_time
      = f.text_field :recommended_time
      = f.label :difficulty
      = f.select :difficulty, Resource.difficulty_ratings
    .submit_button
      = f.submit "Add Resource", class: "btn btn-primary"
      = link_to "<i class='icon-remove'></i> Close".html_safe, "#", class: "close_modal btn btn-inverse"

app/views/resources/_index.html.haml
#resource
  .stoneheader
    .wrapper
      .title
        %i{ class: 'icon-bookmark' }
          = truncate(stone.title, length: 50)
      .links
        = link_to "Add Resource", new_stone_resource_path(stone), remote: true, class: "add_resource_link btn btn-primary"
        - if goal.nil? && user_signed_in?
          = link_to "Add To Your Goals", stone_stones_users_path(stone), class: "btn btn-primary add_goal", remote: true, method: :post
    .description
      %h3= truncate(stone.description, length: 100)
  .filters
    .btn-group
      = link_to 'All', '#', class: "btn filter"
      = link_to 'Beginner', '#', class: "btn filter"
      = link_to 'Intermediate', '#', class: "btn filter"
      = link_to 'Advanced', '#', class: "btn filter"
      = link_to 'Expert', '#', class: "btn filter"
    .btn-group
      = link_to "<i class='icon-sort-by-alphabet'></i>".html_safe, '#', class: "btn sort", data: { sort: 'ASC' }
      = link_to "<i class='icon-sort-by-alphabet-alt'></i>".html_safe, '#', class: "btn sort", data: { sort: 'DESC' }
      = link_to "<i class='icon-sort-by-attributes-alt'></i>".html_safe, '#', class: "btn sort", data: { sort: 'TOP' }
      = link_to "<i class='icon-sort-by-attributes'></i>".html_safe, '#', class: "btn sort", data: { sort: 'BOTTOM' }
      = link_to "Sort", "#", class: "btn sort", data: { sort: "Sort" }
  .resources
    .no_resources_message
      - if stone.resources_stones.empty?
        This topic has no resources. Try populating it with #{ link_to "Google Search", '#', remote: true, class: 'get_auto_resources' }
    = render partial: 'resources/resources_stone', collection: stone.resources_stones, as: :resources_stone

app/views/resources/_resources_stone.html.haml
.resource.votable{ style: "background-image: url(#{resources_stone.resource.photo});", class: "#{resources_stone.resource.difficulty} All", data: { id: "#{resources_stone.id}" }}
  %ul.toolbar_options
    %li
      = link_to "<i class='icon-plus icon-2x'></i>".html_safe,resources_stone_saved_resources_path(resources_stone), remote: true, method: :post, class: "save_resource"
    %li
      = link_to "<i class='icon-facebook-sign icon-2x'></i>".html_safe, "https://www.facebook.com/sharer/sharer.php?u=#{resources_stone.resource.url}"
    %li  
      = link_to "<i class='icon-thumbs-up icon-2x'></i>".html_safe, resources_stone_votes_path(resources_stone.id), class: 'vote', data: { id: resources_stone.id, value: 1, class_name: "ResourcesStone" }
    %li
      = link_to "#{resources_stone.vote_tally}".html_safe, "#", class: 'vote_tally'
  %p.title= truncate(resources_stone.resource.title, length: 30)